### ISSUE TITLE
Error in logs while game is loading

### ISSUE THREAD

**Issue by aburone** [Sirttas/DataPack-Anvil#2]
dpanvil-1.16.5-1.2.1.jar

Nothing critical, but it's annoying when looking for a particular error

[22Jun2021 12:25:37.071] [Worker-Main-7/ERROR] [dpanvil/]: Couldn't delay JEI loading: 
java.lang.NoSuchFieldException: MODDED_REMOTE
  at java.lang.Class.getField(Class.java:1999) ~[?:?]
  at sirttas.dpanvil.interaction.jei.JeiLoadDelayer.setup(JeiLoadDelayer.java:27) ~[dpanvil:1.16.5-1.2.1]
  at sirttas.dpanvil.data.network.proxy.ClientProxy.setupClient(ClientProxy.java:29) ~[dpanvil:1.16.5-1.2.1]
  at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
  at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
  at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
  at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1]
  at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?]
  at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
  at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?]
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
  at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
  at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]

**Comment by Sirttas** [comment]
This error is here for a reason and will stay. This means that this sub module is not compatible with latest versions of jei and I need to update it.

**Comment by Sirttas** [comment]
fixed in 1.2.2
